"""Add automation tables

Revision ID: 5d94f06feda1
Revises: 0940aee27dc1
Create Date: 2026-06-30 22:51:10.846711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d94f06feda1'
down_revision: Union[str, Sequence[str], None] = '0940aee27dc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_request', sa.Text(), nullable=False),
    sa.Column('generated_command', sa.Text(), nullable=False),
    sa.Column('approval_result', sa.String(), nullable=False),
    sa.Column('execution_duration', sa.Float(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('log_content', sa.Text(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('finish_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_records')
    op.drop_table('audit_logs')
    op.drop_table('approval_requests')
    # ### end Alembic commands ###
